// ---------- Resonators data (resonators.js) ----------
const resonators = [
  {
    name: "Augusta",
    weapon: "Broadblade",
    attribute: "Electro",
    nation: "Septimont",
    bossMaterial: "Blighted Crown of Puppet King",
    img: "images/Augusta.png",
    patch: "2.6",
    bond: "With the blazing sun as witness... Glory, bow before us",
    signatureWeapon: "Thunderflare Dominion"
  },
  {
    name: "Brant",
    weapon: "Sword",
    attribute: "Fusion",
    nation: "Rinascita",
    bossMaterial: "Blazing Bone",
    img: "images/Brant.png",
    patch: "2.1",
    bond: "The curtains pull back and I'm here to hunt for every laugh! ..., at your service",
    signatureWeapon: "Unflickering Valor"
  },
  {
    name: "Calcharo",
    weapon: "Broadblade",
    attribute: "Electro",
    nation: "The Federation",
    bossMaterial: "Thundering Tacet Core",
    img: "images/Calcharo.png",
    patch: "1.0",
    bond: "I'll handle your commission, alone.",
    signatureWeapon: ""
  },
  {
    name: "Camellya",
    weapon: "Sword",
    attribute: "Havoc",
    nation: "Unknown",
    bossMaterial: "Topological Confinement",
    img: "images/Camellya.png",
    patch: "1.4",
    bond: "Oh! Hehe... I'm looking forward to our game.",
    signatureWeapon: "Red Spring"
  },
  {
    name: "Cantarella",
    weapon: "Rectifier",
    attribute: "Havoc",
    nation: "Rinascita",
    bossMaterial: "Cleansing Conch",
    img: "images/Cantarella.png",
    patch: "2.2",
    bond: "The sea is a mirror. It reflects the shape of your soul in its tides.",
    signatureWeapon: "Whispers of Sirens"
  },
  {
    name: "Carlotta",
    weapon: "Pistol",
    attribute: "Glacio",
    nation: "Rinascita",
    bossMaterial: "Platinum Core",
    img: "images/Carlotta.png",
    patch: "2.0",
    bond: "Fate has led you to me, and considering the terms I'm offering… You wouldn't refuse me, would you?",
    signatureWeapon: "The Last Dance"
  },
  {
    name: "Cartethyia",
    weapon: "Sword",
    attribute: "Aero",
    nation: "Rinascita",
    bossMaterial: "Unfading Glory",
    img: "images/Cartethyia.png",
    patch: "2.4",
    bond: "The crown of winds... has been engulfed by the sea. Tell me, are you the one who summoned this blade?",
    signatureWeapon: "Defier's Thorn"
  },
  {
    name: "Changli",
    weapon: "Sword",
    attribute: "Fusion",
    nation: "Huanglong",
    bossMaterial: "Rage Tacet Core",
    img: "images/Changli.png",
    patch: "1.1",
    bond: "Eons of time on this vast land, all encapsulated in a humble game...I am fortunate to have you as my opponent.",
    signatureWeapon: "Blazing Brilliance"
  },
  {
    name: "Ciaccona",
    weapon: "Pistol",
    attribute: "Aero",
    nation: "Rinascita",
    bossMaterial: "Blazing Bone",
    img: "images/Ciaccona.png",
    patch: "2.3",
    bond: "Hear that? A twinkling star just tinkled to the ground!",
    signatureWeapon: "Woodland Aria"
  },
  {
    name: "Encore",
    weapon: "Rectifier",
    attribute: "Fusion",
    nation: "New Federation",
    bossMaterial: "Rage Tacet Core",
    img: "images/Encore.png",
    patch: "1.0",
    bond: "Woah! Hey! Woolies, make some room! I wanna look, see? ...Black Shores member, ..., reporting in!",
    signatureWeapon: ""
  },
  {
    name: "Iuno",
    weapon: "Gauntlets",
    attribute: "Aero",
    nation: "Septimont",
    bossMaterial: "Abyssal Husk",
    img: "images/Iuno.png",
    patch: "2.6",
    bond: "While the moon cycles, I remain the anchor.",
    signatureWeapon: "Moongazer's Sigil"
  },
  {
    name: "Jianxin",
    weapon: "Gauntlets",
    attribute: "Aero",
    nation: "Huanglong",
    bossMaterial: "Roaring Rock Fist",
    img: "images/Jianxin.png",
    patch: "1.0",
    bond: "Release the wants, and the mind quiets. Cleanse the thoughts, and the soul clears.",
    signatureWeapon: ""
  },
  {
    name: "Jinhsi",
    weapon: "Broadblade",
    attribute: "Spectro",
    nation: "Huanglong",
    bossMaterial: "Elegy Tacet Core",
    img: "images/Jinhsi.png",
    patch: "1.1",
    bond: "As the Sentinel foretold, you and I were meant to cross paths.",
    signatureWeapon: "Ages of Harvest"
  },
  {
    name: "Jiyan",
    weapon: "Broadblade",
    attribute: "Aero",
    nation: "Huanglong",
    bossMaterial: "Roaring Rock Fist",
    img: "images/Jiyan.png",
    patch: "1.0",
    bond: "I have never regretted to brave the long night.",
    signatureWeapon: "Verdant Summit"
  },
  {
    name: "Lingyang",
    weapon: "Gauntlets",
    attribute: "Glacio",
    nation: "Mt. Firmament",
    bossMaterial: "Sound-Keeping Tacet Core",
    img: "images/Lingyang.png",
    patch: "1.0",
    bond: "Opening greeting — Foul spirits begone, all safe and sound!",
    signatureWeapon: ""
  },
  {
    name: "Lupa",
    weapon: "Broadblade",
    attribute: "Fusion",
    nation: "Rinascita",
    bossMaterial: "Unfading Glory",
    img: "images/Lupa.png",
    patch: "2.4",
    bond: "Oh, is a new match calling?",
    signatureWeapon: "Wildfire Mark"
  },
  {
    name: "Phoebe",
    weapon: "Rectifier",
    attribute: "Spectro",
    nation: "Rinascita",
    bossMaterial: "Cleansing Conch",
    img: "images/Phoebe.png",
    patch: "2.1",
    bond: "Praise the Sentinel. May They guide you to compassion and enlightenment.",
    signatureWeapon: "Luminous Hymn"
  },
  {
    name: "Phrolova",
    weapon: "Rectifier",
    attribute: "Havoc",
    nation: "Fractsidus",
    bossMaterial: "Truth in Lies",
    img: "images/Phrolova.png",
    patch: "2.5",
    bond: "Come, let us finish this performance we've all been waiting for. Together.",
    signatureWeapon: "Lethean Elegy"
  },
  {
    name: "Roccia",
    weapon: "Gauntlets",
    attribute: "Havoc",
    nation: "Rinascita",
    bossMaterial: "Cleansing Conch",
    img: "images/Roccia.png",
    patch: "2.0",
    bond: "All the world's a stage, and we are mere players.",
    signatureWeapon: "Tragicomedy"
  },
  {
    name: "Rover",
    weapon: "Sword",
    attribute: "Spectro",
    nation: "",
    bossMaterial: "Mysterious Code",
    img: "images/Rover.png",
    patch: "1.0",
    bond: "",
    signatureWeapon: "Bloodpact's Pledge"
  },
  {
    name: "Shorekeeper",
    weapon: "Rectifier",
    attribute: "Spectro",
    nation: "Black Shores",
    bossMaterial: "Topological Confinement",
    img: "images/Shorekeeper.png",
    patch: "1.3",
    bond: "This name suits me well enough. It aligns with my purpose and drive: they only exist because of you.",
    signatureWeapon: "Stellar Symphony"
  },
  {
    name: "Verina",
    weapon: "Rectifier",
    attribute: "Spectro",
    nation: "Huanglong",
    bossMaterial: "Elegy Tacet Core",
    img: "images/Verina.png",
    patch: "1.0",
    bond: "This flower is for you. I hope it makes you happy!",
    signatureWeapon: ""
  },
  {
    name: "Xiangli Yao",
    weapon: "Gauntlets",
    attribute: "Electro",
    nation: "Huanglong",
    bossMaterial: "Hidden Thunder Tacet Core",
    img: "images/XiangliYao.png",
    patch: "1.2",
    bond: "As truthseekers, we gauge the universe from within a nutshell. I'd love to hear your insights.",
    signatureWeapon: "Verity's Handle"
  },
  {
    name: "Yinlin",
    weapon: "Rectifier",
    attribute: "Electro",
    nation: "Huanglong",
    bossMaterial: "Group Abomination Tacet Core",
    img: "images/Yinlin.png",
    patch: "1.0",
    bond: "What's that look on your face? Surprised to see me?",
    signatureWeapon: "Stringmaster"
  },
  {
    name: "Zani",
    weapon: "Gauntlets",
    attribute: "Spectro",
    nation: "Rinascita",
    bossMaterial: "Platinum Core",
    img: "images/Zani.png",
    patch: "2.3",
    bond: "Alright, what's the first thing on today's to-do list?",
    signatureWeapon: "Blazing Justice"
  },
  {
    name: "Zhezhi",
    weapon: "Rectifier",
    attribute: "Glacio",
    nation: "Huanglong",
    bossMaterial: "Sound-Keeping Tacet Core",
    img: "images/Zhezhi.png",
    patch: "1.2",
    bond: "What I wanted to say is, the sunlight on you right now is so beautiful. Can I... paint you?",
    signatureWeapon: "Rime-Drapped Sprouts"
  }
]
